name: Deploy to Ubuntu Server

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Build Docker images
        run: |
          docker build . -t overal-x:${{ github.sha }}

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: remove old container
        run: |
          docker rm --force overal-x

      - name: run new container
        run: |
          docker run -d --restart unless-stopped --name overal-x -p 6100:3000 overal-x:${{ github.sha }}
